### ISSUE TITLE
Legacy Kit

### ISSUE THREAD

**Issue by jhunt** [genesis-community/genesis#262]
Build a `legacy` kit that will help to bring pre-v2 and pre-Genesis deployments into the fold of Genesis-y goodness.

## Example 1: Migrating from Genesis v1 to v2

```
kit:
  name: legacy
  features:
    - genesis-v1

params:
  genesis_v1_root:   legacy/cf-deployments/
  genesis_v1_global: global
  genesis_v1_site:   vsphere
  genesis_v1_env:    sandbox
```

Here, the `genesis-v1` feature of the Legacy kit enables a mode for the blueprint hook to lookup things in `params.genesis_v1_*` to figure out where the v1 legacy deployment repo got put.  In this case, it's the `cf-deployments` directory inside of `legacy` in the root of the v2 repo.  Hopefully, this is not a git submodule.  Then, blueprint can glob all of the files the way v1 did, in-order from global → site → environment.

This allows v1 installations to seamlessly adjust to a v2 + cloud-config environment, while working towards deployment similarity with what current kit versions craft.  This will hopefully culminate in a final cut-over to using a v2 kit proper, and the retirement of the legacy kit for this environment and type of deployment.

## Example 2: Migrating from a bespoke, all-in-one Manifest

```
kit:
  name: legacy
  features:
    - manifest
params:
  env:   ...
  bosh:  ...

# $(cat path/to/manifest.yml)
```

This allows people to download their entire manifest from BOSH, and import it into a v2-style env file with an eye towards the same migration path to using a v2 Genesis Kit.

## Example 3: v2 Manifests with Ops Files (i.e. cf-deployment)

```
kit:
  name: legacy
  features:
    - opsfiles

params:
  env: ...
  bosh: ...

  base_manifest: cf-deployment/cf.yml
  ops_files:
    - cf-deployment/operations/aws.yml
  vars:
    input-var: thing
    # ...
```

This is in the same vein of examples 1 and 2, in terms of goals and future state, but caters to people who may want to port their *-deployment deployments to Genesis.
