### ISSUE TITLE
Allow x509 extensions to be specified when creating certificates

### ISSUE THREAD

**Issue by daviddob** [genesis-community/genesis#321]
Allow x509 extensions to be specified via the following (or similar) manner when generating certs.
This is required for OpenVPN and a few other releases.
```
ca: { valid_for: 1y }
      server:
        valid_for: 6m
        names:
          - server.openvpn
        extensions:
          - server_auth
          - digital_signature
          - key_encipherment
```
