### ISSUE TITLE
To Investigate: manifest not being committed during pipeline

### ISSUE THREAD

**Issue by dennisjbell** [genesis-community/genesis#359]
While validating an unrelated change to the ci-pipeline-deploy code, I had to manually create what the pipeline does on my local machine.  This included setting up all the env vars and isolating home to be as empty as it is in the concourse worker.  I then proceeded to perform the steps manually according to the following pipeline task:

```
- name: mystuff-sandbox
  plan:
  - do:
    - aggregate:
      - get: mystuff-sandbox-cloud-config
        trigger: true
      - get: mystuff-sandbox-runtime-config
        trigger: true
      - get: mystuff-sandbox-changes
        trigger: true
    - config:
        container_limits: {}
        image_resource:
          source:
            repository: starkandwayne/concourse
            tag: latest
          type: docker-image
        inputs:
        - name: mystuff-sandbox-changes
        outputs:
        - name: out
        params:
          BOSH_CA_CERT: ...
          BOSH_CLIENT: admin
          BOSH_CLIENT_SECRET: ...
          BOSH_ENVIRONMENT: ...
          BOSH_NON_INTERACTIVE: "true"
          CACHE_DIR: mystuff-sandbox-cache
          CI_NO_REDACT: "0"
          CURRENT_ENV: mystuff-sandbox
          GENESIS_HONOR_ENV: "1"
          GIT_BRANCH: master
          GIT_PRIVATE_KEY: ...
          OUT_DIR: out/git
          PREVIOUS_ENV: ""
          VAULT_ADDR:
          VAULT_ROLE_ID:
          VAULT_SECRET_ID:
          VAULT_SKIP_VERIFY: "1"
          WORKING_DIR: mystuff-sandbox-changes
        platform: linux
        run:
          args:
          - ci-pipeline-deploy
          path: mystuff-sandbox-changes/.genesis/bin/genesis
      ensure:
        params:
          repository: out/git
        put: git
      task: bosh-deploy
    - config:
        container_limits: {}
        image_resource:
          source:
            repository: starkandwayne/concourse
            tag: latest
          type: docker-image
        inputs:
        - name: out
        - name: mystuff-sandbox-changes
        outputs:
        - name: cache-out
        params:
          CI_NO_REDACT: "0"
          CURRENT_ENV: mystuff-sandbox
          GENESIS_HONOR_ENV: "1"
          GIT_BRANCH: master
          GIT_PRIVATE_KEY: ...
          OUT_DIR: cache-out/git
          WORKING_DIR: out/git
        platform: linux
        run:
          args:
          - ci-generate-cache
          path: c-aws-ue1-sandbox-changes/.genesis/bin/genesis
      task: generate-cache
    - params:
        repository: cache-out/git
      put: git
    - params:
        repository: cache-out/git
      put: mystuff-cache
  public: true
  serial: true
```

So, manually, I created the `mystuff-sandbox-change` content by cloning from the deployment repo, set up the environment variables for the `ci-pipeline-deploy` task, set `$HOME` to the directory that `mystuff-sandbox-change` was created in (an otherwise clean directory).

I ran genesis `ci-pipeline-deploy` which deployed the `mystuff-sandbox` environment, and created the out/git changes.

I then setup the environment variables for the `ci-generate-cache` task and ran it.  The result was that the cache-out/git was created, and populated with the cached files and the git history showed the commit `CI commit: generated cache for mystuff-sandbox`.

However, what was missing was the commit from out/git, the `CI commit: deployed to mystuff-sandbox` commit.  So when the `put: git` and `put: mystuff-cache`, both of which point to `cache-out/git`, it run, the manifest does not get pushed up to the repo.

The reason this needs to be investigated further is that the source pipeline was given to me as it was the pipeline that was failing due the previous issue, and we need to verify that it indeed represents a `genesis repipe`-generated pipeline for this task.
