### ISSUE TITLE
Kit authoring document references undocumented gen operator

### ISSUE THREAD

**Issue by VasylTretiakov** [genesis-community/genesis#363]
AUTHORING-KITS.md reads (please note last line of YAML file content):

> Time for an example. If you want your kit to generate a **random**, 40-character password for the admin account, you can put this in your kit.yml:
```
credentials:
  base:
    users/admin:
      password: gen 40
```
**gen** operator is either undocumented or, more likely, should be replaced with the **random** operator which is well-documented below.
