### ISSUE TITLE
Argument "s" isn't numeric in numeric eq... Vault.pm line 462

### ISSUE THREAD

**Issue by tpoland** [genesis-community/genesis#481]
Verifying availability of vault 'foo' (https://vault.lab.mydomain.com/)...Argument "s" isn't numeric in numeric eq (==) at /Users/fflintstone/lab/deployments//.geese/lib/Genesis/Vault.pm line 462.

```
	my ($out,$rc) = $self->query({stderr => "&1"}, "vault", "status");
	if ($rc != 0) {
		$out =~ /exit status ([0-9])/;
		return "sealed" if $1 == 2;     <<<<---- line 462
		return "unreachable";
	}

	return "u
```

This results when the user has multiple safe targets (~/.saferc) pointing at the same vault url:

```
version: 1
current: foo
vaults:
  foo:
    url: https://vault.lab.mydomain.com
    token: s...
    skip_verify: true
  bar:
    url: https://vault.lab.mydomain.com
    token: s...
    skip_verify: true
```
