### ISSUE TITLE
Question on using Spruce operators in ci.yml

### ISSUE THREAD

**Issue by a2geek** [genesis-community/genesis#485]
I'm working on making the `update-genesis-assets` pipeline create a PR request. The original plan was to just modify the _generated_ pipeline as part of the `genesis repipe` command. From what I've been able to determine, Genesis does a `spruce merge ci.yml` first, so modifications cannot be done then and if I do a `defer` action, those actions just end up in the resulting pipeline.

Are there any options within the Genesis repipe command to handle this type of activity without just copying the pipeline outright?

As a sample, these are the commands I've used. If I generate the pipeline in it's entirety and then do a spruce merge, this results in the correct pipeline. I am unable to figure out how to do this directly from the `ci.yml`.

```
jobs:
- name: update-genesis-assets
  plan:
  - (( delete 4 ))
  - (( insert after 1 ))
  - task: create-branch
  - (( append ))
  - task: create-pr-request
```

Thanks!
